# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choicemaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('chosen_answer', models.CharField(max_length=200)),
                ('correct_answer', models.CharField(max_length=200)),
                ('choice_correct', models.BooleanField(default=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='choicemaster.Exam')),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='question',
            name='right_answer_id',
        ),
        migrations.AddField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
