# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choicemaster', '0002_auto_20161025_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_algorithm',
            field=models.CharField(
                default=0,
                max_length=200),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_subject',
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to='choicemaster.Subject'),
        ),
        migrations.AddField(
            model_name='questionsnapshot',
            name='question',
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to='choicemaster.Question'),
        ),
    ]
