# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choicemaster', '0003_auto_20161101_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='topic',
            field=models.ManyToManyField(to='choicemaster.Topic'),
        ),
    ]
