# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choicemaster', '0004_exam_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='exam_subject',
            new_name='subject',
        ),
    ]
