# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choicemaster', '0005_auto_20161101_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='amount_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exam',
            name='mistakes',
            field=models.TextField(default='{}', null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(related_name='questions', to='choicemaster.Question'),
        ),
        migrations.AddField(
            model_name='exam',
            name='questions_used',
            field=models.ManyToManyField(related_name='used', to='choicemaster.Question'),
        ),
        migrations.AddField(
            model_name='exam',
            name='remaining',
            field=models.IntegerField(default=0),
        ),
    ]
